### ISSUE TITLE
This not giving the shortest path

### ISSUE THREAD

**Issue by Talkwondo** [noamsauerutley/breadth-first-search#1]
Hello,
First of all thanks for sharing your explanation about trees and BFS, but I want to enlighten you that your algorithm/code does not return the shortest path. It is return Boolean if the number exists, which in this case it is much better to use DFS. Then, in your alternative BFS it returns the path of the meeting nodes and not the shortest path. Please review my comment here. Thanks

**Comment by noamsauerutley** [comment]
Hi!

Thanks for pointing this out. As discussed in the accompanying blog post¹, this is introductory exploration of breadth first search, which is relevant background for solving the shortest path problem, not a solution to the shortest path problem itself. Actual solutions to the shortest path problem are explored in: [Finding the Shortest Path in Javascript: Djikstra's Algorithm](https://levelup.gitconnected.com/finding-the-shortest-path-in-javascript-dijkstras-algorithm-8d16451eea34) and [the accompanying github repo](https://github.com/noamsauerutley/shortest-path)

I'm sorry for any confusion!

¹ "Is a breadth first search alone a sufficient way to find the shortest path between points on a more complex graph that would be relevant to a real-world mapping challenge? No. Is it a great way to get started exploring this problem? ...yes."
